# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-22 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regloginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
